### ISSUE TITLE
Button 'Create Process' does not work

### ISSUE THREAD

**Issue by SORC3r3r** [process-engine/charon#17]
The 'Create Process' Button does not work.

Pushing the button calls:
/#/start/cc8c62d0-051e-4245-a3eb-02c3f2b9e94a

The uuid is hard coded in the charon code.
The uuid does not belong to the 'Prozess erstellen' process.

Maybe hard coding the id is not the best way?
But if it is, I think it should be something like:
/#/processdef/<PROCESS_UUID>/start

Regards

**Comment by ppoetschke** [comment]
I think its alresdy fixed but not yet published. We check this.

**Comment by heikomat** [comment]
@SORC3r3r this is a known bug, but thanks for the issue! The problem with the startButton-processId is, that the id of that process changes every time the database gets setup again.

You can currently create new processes, by opening the "Prozess erstellen"-process, and hitting "start".

The solution would be to ask the backend for the ID of the start-process, instead of having it hardcoded.

**Comment by ppoetschke** [comment]
@heikomat The solution would be to have a consumer api, to get a process started by key and not by an internal id. You should reference this issue appropriately.

**Comment by heikomat** [comment]
@ppoetschke good idea, as i'm currently working on the consumer_client anyway, i'll add this functionality
