### ISSUE TITLE
[WIP] Missing support of ProcessModels versions

### ISSUE THREAD

**Issue by moellenbeck** [process-engine/charon#83]
#### Describe your issue

@ppoetschke please support the necessary infos.
@moellenbeck Please see comment below.

#### How can others reproduce the issue?

> Describe how others can reproduce this issue as precisely as possible.
> 
> If you can't reproduce the issue, let us know what you tried!
> 
> You can remove this section if the issue isn't something reproducable
> (for example for certain questions or feature requests).

#### Possible solution

> If you have a possible solution to this issue or an idea that might
> help us to find one, describe it here. Let us know what you tried!
>
> You can remove this section if it'd be empty.

#### What's your setup

- OS (`Windows/OS X/Linux` + `version`):
- Node (`node --version`):
- NPM (`npm --version`):
- Docker (`docker version --format '{{.Server.Version}}'`):

> You can remove this section if it's irrelevant to the issue
> (for example for certain questions or feature requests).

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [ ] I've checked if this issue already exists
- [ ] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [ ] I've mentioned PRs and issues that relate to this one

**Comment by ppoetschke** [comment]
To correctly implement current iteration of versioning the entity methods **ProcessDef.getDraft()**, **ProcessDef.publishDraft()** and **ProcessDef.getLatest()** have to be used instead of querying the entity type ProcessDef directly or changing the attributes draft or latest outside of the context of these methods.
- The version is entered manually by the user as process property in the bpmn itself.
- Only process models with the attribute draft set to true can be updated by the method updateDefinitions.
- getDraft() automatically creates a copy of the latest version of processDef, if there isn't a draft yet.
